### ISSUE TITLE
Date of Birth

### ISSUE THREAD

**Issue by Metroxe** [Metroxe/composite-data#4]
date of birth should be an object of type Date, this is a primitive in typescript and js, please read about it here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

There should also be 2 public functions on the date type called is 18 years old, and isOlderThan (takes in a date and checks if older than).

**Comment by raymondchiu10** [comment]
resolved DOB validation, accounting for leap years as well

**Comment by Metroxe** [comment]
Fixed using moment
