### ISSUE TITLE
Zip Code

### ISSUE THREAD

**Issue by Metroxe** [Metroxe/composite-data#6]
This one needs to make sure it is a valid zip code in the united states, if there is an easy way to do this locally, then implement that check, if not feel free to use an api, and return a promise with a boolean instead

**Comment by SpencerGrayp** [comment]
Completed with 5 and 9 digit checks. Matthew said validating the existence of ZIPs can come later if at all

**Comment by Metroxe** [comment]
looks good, just changed `zipcode` to `ZipCode` for camel case purposes
